### ISSUE TITLE
USB redirects to boot picker

### ISSUE THREAD

**Issue by lyiriyah** [drasbeck/macos-thinkpad-t430#20]
Hi,

I'm having an issue where my USB doesn't boot, but instead redirects to boot picker.
I'm using custom kexts for my laptop (Thinkpad T430) from here.

lyiriyah

(Just to clarify, that's BIOS boot picker, not GRUB or Clover)

_**Update**_ 
I've now got as far as End RandomSeed and a string of plusses and then it hangs. I found a [Reddit post](bit.ly/2ITi64G) saying I should add AptioMemoryFix to my drivers64UEFI folder but that post was by someone on Z370, so I don't know if I should do that or not.

**Comment by lyiriyah** [comment]
I followed the BIOS settings posted by @123marvin123 in #11 and they got me as far as End RandomSeed.

**Comment by crisscross231** [comment]
regarding to ur update, there's no reason you shouldn't use the aptiomemoryfix driver

**Comment by drasbeck** [comment]
Only use AptioMemoryFix if you removed the other Aptio drivers, i.e., anything resembling OsxAptioFixDrv. With that said, _do_ use AptioMemoryFix as it is the general notion that it is better.

**Comment by drasbeck** [comment]
@lyiriyah did you ever succeed in your endeavors?

**Comment by lyiriyah** [comment]
No I did'nt

GitHub: AtariVSega | Twitter: lyiriyah
