### ISSUE TITLE
Random kp

### ISSUE THREAD

**Issue by karnadii** [drasbeck/macos-thinkpad-t430#24]
can someone help me? sometimes I face kernel panic while booting. video https://youtu.be/m33HjoZ1wtA. this is my first hackintosh and I already follows all the readme.

my EFI  file https://github.com/karnadii/t430

**Comment by karnadii** [comment]
I don't know why but I don't get random kp anymore.

**Comment by carlosroberto555** [comment]
Well, 4 months later I had this issue too, to fix I just did downgrade to 10.14.3
This version is really stable on my T430

**Comment by karnadii** [comment]
thanks for the info, I'll try to downgrade it if random kp stilll happening.
